name: Simple Web Application Deployment
on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy to Apache Web Server on Azure
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout the Code
      uses: actions/checkout@v2.4.2
    - name: Copy the files
      env:
        azure_user: ${{ secrets.AZURE_USER }}
        azure_key: ${{ secrets.AZURE_KEY }}
        azure_vm: ${{ secrets.AZURE_VM}}
      run: | 
        echo $azure_key > devapacheserver_key.pem
        scp -i devapacheserver_key.pem *.html $azure_user@$azure_vm:/home/$azure_user/
         
