name: Simple Web Application Deployment
on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy to Apache Web Server on Azure
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout the Code
      uses: actions/checkout@v2.4.2
    - name: Copy the files
      env:
        AZURE_USER: ${{ secrets.AZURE_USER }}
        AZURE_KEY: ${{ secrets.AZURE_KEY }}
        AZURE_VM: ${{ secrets.AZURE_VM}}
      run: | 
        echo $AZURE_KEY > devapacheserver_key.pem
        cat devapacheserver_key.pem
        scp -i devapacheserver_key.pem *.html $AZURE_USER@$AZURE_VM:/home/$AZURE_USER/
         
