name: Simple Web Application Deployment
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout the Code
      run: |
        echo "Current Working Directory: $PWD"
        pwd
        echo "Print the List of Files"
        ls -la
        echo "Print the Files in the Folder"
        ls -la asdfasdfasdf
