name: Simple Web Application Deployment
on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy to Apache Web Server on Azure
    runs-on: ubuntu-latest
    env:
      AZURE_USER: ${{ secrets.AZURE_USER }}
      AZURE_KEY: ${{ secrets.AZURE_KEY }}
      AZURE_VM: ${{ secrets.AZURE_VM}}
      ZIP_FILE: "githubtrainingwebsite.tar.gz"
    steps: 
    - name: Checkout the Code
      uses: actions/checkout@v2.4.2

    - name: Zip the files
      run: |
        echo "Zip the files"
        tar -cvzf $ZIP_FILE src

    - name: Copy the files
      run: | 
        echo "$AZURE_KEY" > devapacheserver_key.pem
        chmod 600 devapacheserver_key.pem
        scp -i devapacheserver_key.pem -o StrictHostKeyChecking=no $ZIP_FILE $AZURE_USER@$AZURE_VM:/tmp/
        ssh -i devapacheserver_key.pem -o StrictHostKeyChecking=no $AZURE_USER@$AZURE_VM "movefiles.sh"
         
