name: Simple Web Application Deployment
on:
  push:
    branches:
    - main

jobs:
  build: 
    name: Build application
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Code
      uses: actions/checkout@v2.4.2

    - name: Set version
      run: |
        sed -i "s/APPVERSION/$GITHUB_RUN_NUMBER/" src/index.html
        sed -i "s/SHA/$GITHUB_RUN_NUMBER/" src/index.html

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: src

  devdeploy:
    name: Deploy to DEV Apache Web Server on Azure
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: webapp
    
    - name: Deploy Web Site
      uses: marcodallasanta/ssh-scp-deploy@v1.2.0
      with: 
        local: 'src/*'
        remote: '/tmp/src/'
        host: ${{secrets.AZURE_DEV_VM}}
        user: ${{secrets.AZURE_USER}}
        key: ${{secrets.AZURE_KEY}}
        ssh_options: -o StrictHostKeyChecking=no
        pre_upload: sudo rm -rf /var/www/html/*
        post_upload: sudo mv /tmp/src/* /var/www/html/
    
  test-web:
    name: Testing Deployment
    runs-on: ubuntu-latest
    needs: [devdeploy]
    steps:
    - name: Verifying version was updated on index.html
      run: wget -qO- ${{ secrets.AZURE_DEV_VM }}/index.html | grep -iq $GITHUB_RUN_NUMBER

    - name: Verifying sha was updated on index.html
      run: wget -qO- ${{ secrets.AZURE_DEV_VM }}/index.html | grep -iq $SHA
  
  testing-network:
    name: Testing Connectivity to Web Server
    runs-on: ubuntu-latest
    needs: [devdeploy]
    steps:
      - name: Using NetCat we will Check the Port
        run: nc -zv ${{secrets.AZURE_DEV_VM }} 80

  proddeploy:
    name: Deploy to PROD Apache Web Server on Azure
    runs-on: ubuntu-latest
    needs: [test-web]
    steps: 
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: webapp
    
    - name: Deploy Web Site
      uses: marcodallasanta/ssh-scp-deploy@v1.2.0
      with: 
        local: 'src/*'
        remote: '/tmp/src/'
        host: ${{secrets.AZURE_PROD_VM}}
        user: ${{secrets.AZURE_USER}}
        key: ${{secrets.AZURE_KEY}}
        ssh_options: -o StrictHostKeyChecking=no
        pre_upload: sudo rm -rf /var/www/html/*
        post_upload: sudo mv /tmp/src/* /var/www/html/