name: Simple Web Application Deployment
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps: 
    - name: Print Statement 2
      run: echo "Hello, All, I am Github Runner"
